name: cicd-test

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: my test
    runs-on: windows-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
    
      - name: Setup path
      - run: set PATH=%PATH%;lib\;external_lib\
      - run: set gspDemoHome=.
      - run: set CLASSPATH=%gspDemoHome%\build;%gspDemoHome%\lib;%gspDemoHome%\lib\*;%gspDemoHome%\external_lib;%gspDemoHome%\external_lib\simple-xml-2.6.2.jar;%gspDemoHome%\external_lib\expr4j.jar;%gspDemoHome%\external_lib\commons-logging-1.1.3.jar;%gspDemoHome%\external_lib\jarLoader.jar;%gspDemoHome%\external_lib\junrar-0.7.jar;%gspDemoHome%\external_lib\fastjson-1.2.41.jar;.;
