name: cicd-test

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: my test
    runs-on: windows-latest
    steps:
      - name: build project
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
           cd setenv
           ./setenv.bat
