name: cicd-test

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: my test
    runs-on: windows-latest
    steps:       
      - name: release
        uses: actions/checkout@master
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      
      - name: set path1
        run: |
          cd setenv
          ./setenv.bat
          
      - shell: bash
        run: |
          expr "set path1 success!" >> ../README.md
    
      - name: build checksyntax and run
        run: |
          cd src/main/java/demos/checksyntax/
          ./compile_checksyntax.bat
          ./run_checksyntax.bat /f test/test.sql /t Orcale
          
      - shell: bash
        run: |
          expr "set path2 success!" >> ../README.md
          
      - name: build gettablecolumns and run
        run: |
          cd src/main/java/demos/gettablecolumns/
          ./compile_gettablecolumns.bat
          ./run_getResultColumn.bat
      
      - shell: bash
        run: |
          expr "set path3 success!" >> ../README.md
