name: cicd-test

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: my test
    runs-on: windows-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
    
      - name: Setup path1
        run: ./src/main/java/demos/checksyntax/compile_checksyntax.bat
